### ISSUE TITLE
projekt.RMd

### ISSUE THREAD

**Issue by mpracek** [mpracek/APPR-2017-18#2]
Datoteka projekt.Rmd se mi ne naloži

**Comment by jaanos** [comment]
Da se ti poročilo prevede, se morajo brez napak izvesti vsi programi, ki jih kličeš v poročilu - pri tebi se zalomi v `uvoz.r`, in sicer pri uporabi funkcije `dcast` na razpredelnici `tidy_nagib`, saj ta nima stolpca `Velikostni.razred` - namesto njega bo potrebno uporabiti stolpec `Nagib`.

Podobno bo treba narediti tudi pri ostalih razpredelnicah, pri čemer svetujem, da presledke v imenih stolpcev (tistih, ki bodo v končni razpredelnici) nadomestiš s pikami, saj bo tako lažje podajati njihova imena funkcijam. Prav tako svetujem, da v imenih stolpcev ne uporabljaš šumnikov.

Opozoril bi te na razpredelnico `tidy_sorte.povrsina_sadike`, kjer sta zamenjani imeni stolpcev za leto in meritev. Pri pretvorbi z `dcast` potem uporabi to razpredelnico (s `tidy_` na začetku). Iz razpredelnice `trsnice.maticnjaki` brišeš tretji stolpec, ki ima podatke o vinorodni deželi - tega ohrani, da bo nadaljnja pretvorba pravilna.

Svetoval bi še, da razpredelnici `bele.sorte` in `rdece.sorte` združiš v eno - vsaki dodaš še stolpec z barvo in združiš z `rbind`. Ponekod imaš poleg države še regijo ali kak komentar, ponekod pa več držav. Svetujem, da regije in komentarje pobrišeš, kjer pa imaš več držav, pa vrstico ponovi za vsako državo - poglej jonagricar#2 za primer.

Vidim, da nekaterih podatkov še nisi uvozil, oziroma si pustil prazno za `<-`. Svetujem, da take vrstice raje zakomentiraš - pri poganjanju sicer ne bo prišlo do napake, bodo pa spremenljivke dobile vrednost iz naslednje vrstice, česar načeloma ne želiš.

Ko to urediš, bo treba iz `projekt.Rmd` odstraniti še del, ki je ostal iz vzorca - torej od risanja histograma naprej. Seveda lahko namesto tega narišeš kak svoj graf. Da ti v poročilo ne bo izpisovalo vseh opozoril, ki se pojavijo ob uvozu, v glavo bloka kode, kjer pokličeš `uvoz.r`, dodaj še parameter `warning = FALSE`.

**Comment by jaanos** [comment]
Na repozitorij za zagovore sem dodal povezavo do commita 6304afe. Pri trenutnem commitu dobim pri prevajanju poročila napako, da ne najde slike `slike/guyot.jpg`. Datoteke s končnico `.jpg` namreč zaradi nastavitve v datoteki `.gitignore` git ignorira - torej ti ne ponudi, da bi jo vključil v commit. Da boš to lahko storil, iz `.gitignore` izbriši vrstico `*.jpg`, pa boš lahko dodal sliko.

V poročilu pazi, da vstaviš prazno vrstico vsakič, ko želiš iti v nov odstavek - enako velja tudi pred seznami in vodoravno črto (`***`). Sezname zamikaj za dva presledka samo takrat, ko začneš nov podseznam, npr.
```R
Vse te tabele imajo podobno izgradnjo;

1. Prvi stolpec je stolpec `leto`
2. Drugi stolpec je stolpec `vinorodna.dezela`
3. Tretji stolpec je opisne spremenljivke, v podanem primeru je to `zatravljenost`
4. V nadaljnih stolpcih pa se nahajajo meritve:
    
  i) `povrsina`,
  ii) `stevilo.sadik`
  iii) `stevilo.vinogradov`
```
Zamik za štiri presledke namreč v Markdownu pomeni prikaz kot blok kode.

Svetoval bi še, da z zemljevida odstraniš imena držav, saj se ta prekrivajo, zemljevid pa ni zaradi tega nič bolj pregleden (kvečjemu manj). Lahko morda poskusiš tudi z zmanjšanjem velikosti pisave.

Ko boš rešil te težave in boš želel posodobiti povezavo, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-zagovori) (glej navodila spodaj).

**Comment by jaanos** [comment]
Vidim, da ti zdaj prevede poročilo, tako da bom posodobil povezavo. Vseeno pa poskrbi še za ostale zadeve.

**Comment by mpracek** [comment]
Pozdravljeni!

Ko zaženem shiny aplikacijo, se mi le ta odpre in takoj sesuje.

**Comment by jaanos** [comment]
V `server.R` ti manjka nekaj zaklepajev. Tako bi moralo delovati:
```R
  output$sorte <- renderText({
    stevilo_sort %>% filter(drzava == input$select) %>%
      transmute(text = paste( drzava, "ima" ,stevilo, "avtohtonih sort." ) %>% as.character())
  })
```
Seveda v `ui.R` poskrbi, da se bo to besedilo dejansko nekje izpisalo.
